version: '3'

networks:
  idea2app:

services:
  web-log:
    image: idea2app/web-log
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - idea2app
  caddy:
    depends_on:
      - web-log
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - idea2app
    command: caddy reverse-proxy --from your.domain.com --to web-log:3000
